[package]
name = "olymbits"
description = "Summer Challenge 2024 with Fiverr - Olymbits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
